version: '2'
services:

  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - all

  mongo:
    image: mongo
    command: mongod --smallfiles
    ports:
      - "27015:27017"
    networks:
      - all

  contacts-service:
    build: contacts-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbit
    networks:
      - all
    environment:
      RABBITMQ_URI: "amqp://rabbit:5672"
      MONGODB_URI: "mongodb://mongo:27017/contacts"

  history-service:
    build: history-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbit
    networks:
      - all
    environment:
      RABBITMQ_URI: "amqp://rabbit:5672"
      MONGODB_URI: "mongodb://mongo:27017/history"

networks:
  all:
