#%RAML 1.0
title: Contacts
version: v1
baseUri: /

types:
  Contact:
    properties:
      id: string
      name: string
      email?: string
      phone?: string
    example:
      id: 'aaaa-bbbb-cccc-dddd'
      name: 'Andrei'
      email: 'andrei@email.com'
      phone: '+3752912312312'

resourceTypes:
  Collection:
    get:
      description: Retrieve contacts list
      responses:
        200:
          body:
            application/json:
              type: <<item>>[]
  Member:
    get:
      description: Retrieve contact
      responses:
        200:
      body:
        application/json:
          type: <<item>>
    post:
      description: Create contact
      responses:
        201:
      body:
        application/json:
          type: <<item>>
    patch:
      description: Modify contact
      responses:
        200:
      body:
        application/json:
          type: <<item>>
    delete:
      description: Delete contact
      responses:
        204:

traits:
  Paged:
    queryParameters:
      limit?:
        type: integer
        description: Specify the amount of contacts that you want to retrieve
        default: 10
        example: 5
      offset?:
        type: integer
        description: Specify the offset starting from which you want to retrieve contacts
        default: 0
        example: 3

/contacts:
  type:  { Collection: {item : Contact} }
  get:
    queryParameters:
    is: [Paged]
  /{id}:
    type:  { Member: {item : Contact} }
